name: daily-scrap
    
on:
  schedule:
    - cron: "40 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Scrap new tweets
        run: |
          python algeria.py
          echo ::set-output name=pr_title::"$(date +%Y-%m-%d) updates"
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ steps.vars.outputs.pr_title }}
          delete-branch: true
          title: ${{ steps.vars.outputs.pr_title }}
